server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 30
#    context-path:项目路径，默认是localhost:8080/
spring:
  application:
    name: springbootDemo4Mybatis
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: c##sample
    password: oracle
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 216
      # 配置获取连接等待超时的时间
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 50MB
      # 设置单次请求文件的总大小
      max-request-size: 50MB
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

# 设置，mapper 接口路径，mapper 接口对应的xml 配置文件
mybatis:
  mapper-locations: classpath:*/mapper/*/*.xml
  #type-aliases-package: com.zcz.dao  #在springboot程序入口类处添加注解@MapperScan("com.zcz.dao")此处可省略，不添加的话这里要写上，每个dao层映射接口也要添加注解@Mapping
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
    map-underscore-to-camel-case: true  #驼峰映射
#sample
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: countSql
  returnPageInfo: check